### ISSUE TITLE
Description part on Event/Client single page allows empty descriptions to be submitted

### ISSUE THREAD

**Issue by ZekTheGreat** [victorhahn/SCIM#114]
![image](https://cloud.githubusercontent.com/assets/25301086/24894229/f7c83a66-1e56-11e7-9874-d1cd5b3a9feb.png)

**Comment by victorhahn** [comment]
should be an easy fix

**Comment by ZekTheGreat** [comment]
Yeah I can fix it now, if needed

**Comment by victorhahn** [comment]
sounds good, if you want to take a crack at it. I'm gonna do a test build to make sure I can use the icon file Paige sent me

**Comment by victorhahn** [comment]
Also if you want to try to add delete functionality you can go for it, but I don't think it's that big of deal either way

**Comment by ZekTheGreat** [comment]
Yeah I can try to add it but it becomes to much of a hassle then I'm not gonna do it

**Comment by victorhahn** [comment]
sounds good, I'd say do the blank event note fix first and push immediately, then if you have time to do delete do that on a separate branch

**Comment by ZekTheGreat** [comment]
Yeah that's what I'm fixing now
