### ISSUE TITLE
Event Time Display

### ISSUE THREAD

**Issue by ZekTheGreat** [victorhahn/SCIM#88]
When setting an event time to start at 12:00pm, the time is stored incorrectly in the database as 12:00am.

**Comment by ZekTheGreat** [comment]
This bug still persist. Start time is still being stored as 'am' even if it needs to be stored as 'pm'

**Comment by Diquirk** [comment]
It's working correctly on my end. Is it when you are trying to update?

**Comment by ZekTheGreat** [comment]
Try it with a purged/clean database. It happens when I add and/or update an event. My start time is 12:00pm and when I check it on the clients single page, the start time is displayed as 12:00 am.

**Comment by ZekTheGreat** [comment]
It's only happening when the start time is 12:00pm

**Comment by Diquirk** [comment]
Oh okay, I'll look at it when I get home. I'm pretty sure I know why it's doing that.

**Comment by ZekTheGreat** [comment]
Okay sounds good man. Just wanted to give you a heads up
