### ISSUE TITLE
Southern Charm Icon for exe

### ISSUE THREAD

**Issue by victorhahn** [victorhahn/SCIM#96]

**Comment by holbrooka2** [comment]
![screenshot 22](https://cloud.githubusercontent.com/assets/25379755/24833596/43ec81a2-1c9c-11e7-8932-00e9a472be9c.png)

Will this work?

**Comment by holbrooka2** [comment]
![screenshot 35](https://cloud.githubusercontent.com/assets/25379755/24833645/6392855a-1c9d-11e7-8d68-0ae5f36086a1.png)
Here it is just for reference if you want that.
